language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: reactiverse-vertx-maven-plugin
    token:
      secure: "s/a5VFbYyomNVymcgpHdX74vHscmmJedwVwOFajYsiArfhvjlpY45s/0ATuvFzWc98qyoQlztcNmIHEtFD3gdJMYoTgz2sEDNUZ4OC5K95SPIMLeYmw/IxXP7IsLqeBwrZX+yjwXzZgkevqMNkdAtKtsSTN/B9XOXuG3zn397WFVA6X4m6psG8YwPOyZafCDEqgauCX19jmaEXwD3e4mzptay3dfzwVV8rghAgrCpc3tSK076nhzYmZZ7LG1L8l1Pk0pvvLLO6YRRDassre07nOQlZcv1GlSVn4Ce/ZcSz7O2q0usyJ3iTU/atovjbdOTB56oybe0kSWosXWFki8r4Az3vkr+IAvAkDf7R56ly7s/CLs7Ka874mLBvVdGWwNXfBV5/3E8TJYRasukNwJOqGRc3AVytcJp7p7TwpQce8kk8MnVoH6k1h4qUoLPSTjt6K12Yee64bukGAG0OrY3vxDU86EtXpnopMhty1qzN/IYAJ14hHKTuqp5USLRpfPTzE21SrV/ZxUBuT4ySxPwAu7SCvwaLPJTj95sDnZnoL7S1I/fHvwG2IwwOT5YyP91l7FTvggXmWvC7X5spviri/wIEwr0loCfJU+FfwKrFHx6tw7g+XoSD80agU3NooAeGkVVfEm5/rKHxPFfBXm0NfkI8WSz2ooqrwxXzBjbTo="
env:
  global:
  - SONATYPE_USERNAME="clement.escoffier"
  - secure: h887vbdiBD8HPV0Ltssu2JIUWVHKHkshxiXu/7uh9ZFQyyzqVWLTjcSeXWqWwKgTVgUtDBtF0OICw7RqKAKzSA2EX+v0A9EzkkR2cqa5EKlii1GJRec7qbteRUIln0ejNHYKo66wzU3p/1AGMGK7b8nAu3jdAViTFgQ2b/1RHSA6lCWsOFMPkQVxGwsexXifWIIps4wCKmFmCN5yzFLOPDfv9bV76jcC5MyUy4KuLW8igm2ygJ8b+O71t3WJNPf12s/mRWcQ5AaRU772l8affbDvDjeud+IHpG7vmWCnCrVd2pLogfLnL/4Uj6uXhLScuHzynqAWRTW2GOrwbBEV5Qz01fcVTE2J1KfEkeQtGhpCWcB/6YQOgilttK0k+nwENxehg2fJgR5ZvxcfO+qkOMWsDNCGHRYKvQlJFHiY3DHsE4DuAKxE8WK5fVMNWA4eslAPJW/NOY5PQ0p8jWo2JSyR/ZvKPtR2z4CpwQcMgrtFIZWe4DhZbf73MedQ7n8qtx+WuBW1iL5fSUMye63VYuTILUTmNotrBSARqonlbZ5iglviZUwB/rm8dNklCNufuuEOeBkCLLuygF2/6mIlYN5X+UL1RZWsy4nx0oMNE6/TAGSoKPjt0DMYSABssPCJ7MRniIDzwhoJ6/CSlAnii29OGzcLEGQ2CXsLeE4NiRs=
script:
- mvn clean install sonar:sonar -Pcoverage -Dsonar.host.url=https://sonarcloud.io/
after_success:
- ".build/deploy-snapshot.sh"
notifications:
  email:
  - clement@apache.org
